"""
Stage 2: Quantize trained model to INT8 TFLite and export as C header for ESP32.

Steps:
  1. Keras .h5 -> TFLite FP32
  2. TFLite FP32 -> TFLite INT8 (with representative dataset calibration)
  3. Verify accuracy drop on validation set
  4. Export as C byte array header

Usage: python quantize_model.py [--validate]
"""

import argparse
import os, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import tensorflow as tf
from pathlib import Path
from sklearn.model_selection import train_test_split
from train_model import load_data
from src.config import SEQ_LEN, N_LANDMARKS


def representative_dataset_gen(X_calib):
    """Generator for representative dataset (calibration for INT8 quantization)."""
    for i in range(len(X_calib)):
        yield [X_calib[i:i+1].astype(np.float32)]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--validate", action="store_true", help="Compare FP32 vs INT8 accuracy")
    parser.add_argument("--model", default="outputs/model.h5")
    args = parser.parse_args()

    model_path = Path(args.model)
    if not model_path.exists():
        raise FileNotFoundError(f"Model not found: {model_path}")

    print("Loading Keras model...")
    model = tf.keras.models.load_model(model_path)

    # Step 1: Convert to TFLite FP32
    print("Converting to TFLite FP32...")
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_fp32 = converter.convert()

    out_dir = Path("outputs")
    fp32_path = out_dir / "model_fp32.tflite"
    fp32_path.write_bytes(tflite_fp32)
    print(f"FP32 model: {len(tflite_fp32) / 1024:.1f} KB -> {fp32_path}")

    # Step 2: Quantize to INT8
    print("Quantizing to INT8...")
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    X, y, classes = load_data()
    _, X_calib = train_test_split(X, test_size=0.2, random_state=42)
    X_calib = X_calib[:500]

    converter.representative_dataset = lambda: representative_dataset_gen(X_calib)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_int8 = converter.convert()

    int8_path = out_dir / "model_int8.tflite"
    int8_path.write_bytes(tflite_int8)
    print(f"INT8 model: {len(tflite_int8) / 1024:.1f} KB -> {int8_path}")

    # Step 3: Validate accuracy
    if args.validate:
        print("Validating INT8 accuracy...")
        _, X_val, _, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

        # FP32 accuracy
        interpreter_fp32 = tf.lite.Interpreter(model_content=tflite_fp32)
        interpreter_fp32.allocate_tensors()
        inp_details = interpreter_fp32.get_input_details()
        out_details = interpreter_fp32.get_output_details()

        correct_fp32 = 0
        correct_int8 = 0
        n = min(len(X_val), 200)

        for i in range(n):
            sample = X_val[i:i+1].astype(np.float32)

            interpreter_fp32.set_tensor(inp_details[0]['index'], sample)
            interpreter_fp32.invoke()
            pred_fp32 = interpreter_fp32.get_tensor(out_details[0]['index'])

            # INT8 requires quantized input
            interpreter_int8 = tf.lite.Interpreter(model_content=tflite_int8)
            interpreter_int8.allocate_tensors()
            inp_details_int8 = interpreter_int8.get_input_details()
            out_details_int8 = interpreter_int8.get_output_details()

            q_params = inp_details_int8[0]['quantization_parameters']
            scale, zero_point = q_params['scales'][0], q_params['zero_points'][0]
            sample_int8 = np.clip(sample / scale + zero_point, -128, 127).astype(np.int8)

            interpreter_int8.set_tensor(inp_details_int8[0]['index'], sample_int8)
            interpreter_int8.invoke()
            pred_int8_q = interpreter_int8.get_tensor(out_details_int8[0]['index'])
            pred_int8 = (pred_int8_q.astype(np.float32) - out_details_int8[0]['quantization_parameters']['zero_points'][0]) * out_details_int8[0]['quantization_parameters']['scales'][0]

            if np.argmax(pred_fp32) == y_val[i]:
                correct_fp32 += 1
            if np.argmax(pred_int8) == y_val[i]:
                correct_int8 += 1

        acc_fp32 = correct_fp32 / n * 100
        acc_int8 = correct_int8 / n * 100
        print(f"FP32 accuracy: {acc_fp32:.1f}%")
        print(f"INT8 accuracy: {acc_int8:.1f}%")
        print(f"Drop: {acc_fp32 - acc_int8:.1f}%")

    # Step 4: Export C header
    c_header_path = out_dir / "model_data.h"
    with open(c_header_path, "w") as f:
        f.write("// Auto-generated by quantize_model.py\n")
        f.write(f"// INT8 quantized CNN model for ESP32 ({len(tflite_int8)} bytes)\n\n")
        f.write("#ifndef MODEL_DATA_H_\n#define MODEL_DATA_H_\n\n")
        f.write("#include <cstdint>\n\n")
        f.write(f"const unsigned char g_model_data[] = {{\n  ")
        for i, byte in enumerate(tflite_int8):
            f.write(f"0x{byte:02x}, ")
            if (i + 1) % 12 == 0:
                f.write("\n  ")
        f.write("\n};\n\n")
        f.write(f"const unsigned int g_model_data_len = {len(tflite_int8)};\n\n")
        f.write("#endif  // MODEL_DATA_H_\n")

    print(f"C header: {c_header_path}")
    print("Done. Model ready for ESP32 deployment.")


if __name__ == "__main__":
    main()
